### ISSUE TITLE
[Bug]: claims that the first attempted code works before crashing

### ISSUE THREAD

**Issue by SMG54321** [Derpitron/Discord-OTP-Forcer#94] opened 2023-11-24 10:09 UTC
### Description

this happens everytime i try to use it. it claims the first code works, but the code doesnt work then it crashes

### Minimal Reproduction

i apologize for being annoying with this. i will provide images down below

### Error

![image](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/54807766-f771-42f7-a105-20b35eed4e59)
![image (1)](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/b4d60687-0fd5-42d7-ab16-aef90d3d8670)

### Operating System Version

Widows 10

### Python Version

3.12

### Program Version 

latest

### Any other information or context?

again, i am very sorry if i am annoying with this if you got the replies i made in email.

**Comment by LuXeZs** [comment] 2023-11-24 10:29
fixed in latest version

**Comment by Derpitron** [comment] 2023-11-25 06:33
@SMG54321 are you sure the codes here didn't work? 

For all we know, the codes could have *actually* logged you in succesfully. 

Intentionally, the Selenium Chrome window does not close if the program halts/crashes. This is so that in case the login works, the user would be able to manage/salvage their account from the Selenium window.

Reopening this issue

**Comment by Derpitron** [comment] 2023-11-28 10:35
Duplicate of #95

**Closed by Derpitron** 2023-11-28 10:35 UTC
Labels: bug
