### ISSUE TITLE
[Bug]: normal mode breaks after a while

### ISSUE THREAD

**Issue by SMG54321** [Derpitron/Discord-OTP-Forcer#92] opened 2023-11-22 11:42 UTC
### Description

while using normal mode, it broke. not sure how!

### Minimal Reproduction

censored name 

### Error

Traceback (most recent call last):
  File "C:\Users\[REDACTED]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\src\backend.py", line 215, in code_entry
    loginTest = driver.find_element(by=By.CLASS_NAME, value='app-2CXKsg')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".app-2CXKsg"}
  (Session info: chrome=119.0.6045.160); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00DE72A3+45731]
        (No symbol) [0x00D72D51]
        (No symbol) [0x00C6880D]
        (No symbol) [0x00C9B940]
        (No symbol) [0x00C9BE0B]
        (No symbol) [0x00CCD1F2]
        (No symbol) [0x00CB8024]
        (No symbol) [0x00CCB7A2]
        (No symbol) [0x00CB7DD6]
        (No symbol) [0x00C931F6]
        (No symbol) [0x00C9439D]
        GetHandleVerifier [0x010F0716+3229462]
        GetHandleVerifier [0x011384C8+3523784]
        GetHandleVerifier [0x0113214C+3498316]
        GetHandleVerifier [0x00E71680+611968]
        (No symbol) [0x00D7CCCC]
        (No symbol) [0x00D78DF8]
        (No symbol) [0x00D78F1D]
        (No symbol) [0x00D6B2C7]
        BaseThreadInitThunk [0x75F1FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770F7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x770F7C3E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[REDACTED]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\main.py", line 68, in <module>
    userFacing(load_configuration())
  File "C:\Users\[REDACTED]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\main.py", line 64, in userFacing
    bootstrap_login_page(driver, configuration)
  File "C:\Users\[REDACTED]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\src\backend.py", line 117, in bootstrap_login_page
    code_entry(driver, login_fields, configuration)
  File "C:\Users\[REDACTED]\Desktop\junk 3 recylcled edition\Discord-OTP-Forcer-main\src\backend.py", line 225, in code_entry
    login_fields['TOTP'].send_keys(Keys.BACKSPACE)
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 230, in send_keys
    self._execute(
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=119.0.6045.160)
Stacktrace:
        GetHandleVerifier [0x00DE72A3+45731]
        (No symbol) [0x00D72D51]
        (No symbol) [0x00C686D0]
        (No symbol) [0x00C98118]
        (No symbol) [0x00C9774F]
        (No symbol) [0x00CB7FDC]
        (No symbol) [0x00C94A4E]
        (No symbol) [0x00CB8254]
        (No symbol) [0x00CCB7A2]
        (No symbol) [0x00CB7DD6]
        (No symbol) [0x00C931F6]
        (No symbol) [0x00C9439D]
        GetHandleVerifier [0x010F0716+3229462]
        GetHandleVerifier [0x011384C8+3523784]
        GetHandleVerifier [0x0113214C+3498316]
        GetHandleVerifier [0x00E71680+611968]
        (No symbol) [0x00D7CCCC]
        (No symbol) [0x00D78DF8]
        (No symbol) [0x00D78F1D]
        (No symbol) [0x00D6B2C7]
        BaseThreadInitThunk [0x75F1FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770F7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x770F7C3E+238]

### Operating System Version

dunno

### Python Version

3.12

### Program Version 

latest

**Comment by LuXeZs** [comment] 2023-11-22 13:41
Does this happen every time you run the program? Also how long does it run before this happens?

**Comment by SMG54321** [comment] 2023-11-22 20:24
I just timed it. It usually works for about 4 minutes and 25 seconds

**Comment by SMG54321** [comment] 2023-11-22 20:56
actually, its verying WILDLY!!! like the most recent was like only 4 or 5 attemps before it gave that error. i think its because its about to attempt the right one but SOMETHING is saying no

**Comment by SMG54321** [comment] 2023-11-23 02:16
actually, can you give me the code that is breaking the program? it might be the right one. to me its un readable as of now

**Comment by SMG54321** [comment] 2023-11-23 02:29
> Does this happen every time you run the program? Also how long does it run before this happens?

yep, can you send me the codes that those exceptions might be producing? they might be the right one?

**Comment by SMG54321** [comment] 2023-11-23 03:20
![image_2023-11-22_201945935](https://github.com/Derpitron/Discord-OTP-Forcer/assets/51088182/80ec3c2f-3aca-458e-8bcc-8552e6d0bfeb)

this attempt broke after one failed code

**Comment by Derpitron** [comment] 2023-11-23 13:15
Don't create duplicate issues of the same bug. This is being worked on.

**Comment by SMG54321** [comment] 2023-11-23 20:05
sorry

**Comment by LuXeZs** [comment] 2023-11-24 06:55
@SMG54321 Could you download the latest version and see if the issue is fixed.

**Comment by SMG54321** [comment] 2023-11-24 07:41
doesnt break at random, but now its saying the first code it tries works
before crashing like this
[image: image.png]

**Comment by SMG54321** [comment] 2023-11-24 07:41
the code did not work BTW

**Comment by SMG54321** [comment] 2023-11-24 07:45
tested it with backup. same problem. might be because i didnt fill out the
disable 2fa part of the cfg.yml. but i dunno
[image: image.png]

**Comment by LuXeZs** [comment] 2023-11-24 10:29
fixed in latest version

**Comment by Derpitron** [comment] 2023-11-24 15:18
After commit d1a5b0359dcd793e3d17846c3fdfb63919b34f13, the program seems to simply not work in my case. Running `py main.py` neither shows an error, nor does it spawn the Selenium window.

My Config:
```yml
# Basic login info
email: "xxx"
password: "xxx"

# Program mode configuration
# Lets you skip the initial mode prompt stage by filling in your desired
# programMode and codeMode beforehand.
programMode: "reset"
codeMode: "normal"

# Password Reset Info
#
# To get your token it will be in the url of the password reset page.
# Follow the instructions in the README.md on how to obtain this token
newPassword: "xxx"
resetToken: "xxx"

# Disable 2FA info
# Fill in your discord account token here.
authToken: ""
```

**Closed** 2023-11-24 15:21 UTC
Labels: bug

**Comment by SMG54321** [comment] 2023-11-24 15:57
ok, even i am admitting, this is starting to get stupid

[image: image.png]
[image: image.png]

My configuration is as follows

# Basic login info
email: "xxx"
password: ""

# Program mode configuration
# Lets you skip the initial mode prompt stage by filling in your desired
# programMode and codeMode beforehand.
programMode: "reset"
codeMode: "normal"

# Password Reset Info
#
# To get your token it will be in the url of the password reset page.
# Follow the instructions in the README.md on how to obtain this token
newPassword: "xxx"
resetToken: "xxx"

# Disable 2FA info
# Fill in your discord account token here.
authToken: ""

i am also running the "start" batch file to activate it if that is
doing anything

**Comment by SMG54321** [comment] 2023-11-24 16:27
might be because i installed selenium and pyYAML seperatly outside of the
"setup" batch file?

could also be the version im using the program on (python 3.12). which
version are you running it on?

i am so sorry for asking questions that might be causing you to bash your
face against the wall!

**Comment by SMG54321** [comment] 2023-11-24 16:35
[image: image.png]
[image: image.png]
